import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Formulário CRP-01",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logocrp.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-br">
      <body className={GeistSans.className}>{children}</body>
    </html>
  );
}
